#ifndef __webasto_h
#define __webasto_h

enum {
  WEBASTO_MODE_DEFAULT = 0x20,
  WEBASTO_MODE_PARKING_HEATER = 0x21,
  WEBASTO_MODE_VENTILATION = 0x22,
  WEBASTO_MODE_SUPPLEMENTAL_HEATER = 0x23,
  WEBASTO_MODE_CIRCULATION_PUMP = 0x24,
  WEBASTO_MODE_BOOST = 0x25,
  WEBASTO_MODE_COOLING = 0x26,			// Custom to this board
};

#endif
