#ifndef __wifi_h_
#define __wifi_h_

#define CBOR_CURRENT_VERSION  1
enum {
  CBOR_VERSION,
  CBOR_FSM_STATE,
  CBOR_FSM_MODE,
  CBOR_BURN_POWER,
  CBOR_FLAME_DETECT,
  CBOR_COMBUSTION_FAN,
  CBOR_VEHICLE_FAN,
  CBOR_INTERNAL_TEMP,
  CBOR_OUTDOOR_TEMP,
  CBOR_COOLANT_TEMP,
  CBOR_EXHAUST_TEMP,
  CBOR_BATTERY_VOLT,
  CBOR_VSYS_VOLT,
  CBOR_GPIOS,
};

enum {
  CBOR_GPIO_START_RUN,
  CBOR_GPIO_IGNITION,
  CBOR_GPIO_EMERG_STOP,
};

void init_cbor(void);
void cbor_send(void);

#endif
