M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Thu 19 Jan 2023 02:12:47 AM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-19T02:12:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.136Y-3.8707
X7.136Y-4.0616
T2
X7.2553Y-3.8589
X7.2553Y-4.0734
T0
M30
