M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date Wed 08 Mar 2023 02:45:40 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-08T14:45:40-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.1366Y-3.8691
X7.1366Y-4.06
T2
X7.2559Y-3.8573
X7.2559Y-4.0719
T0
M30
