M48
; DRILL file {KiCad (6.0.10)} date Tue Jan 31 02:16:07 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-31T02:16:07-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.136Y-3.8707
X7.136Y-4.0616
T2
X7.2553Y-3.8589
X7.2553Y-4.0734
T0
M30
