M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Tue 31 Jan 2023 02:27:39 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-31T14:27:39-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X7.1325Y-2.2591
X7.3234Y-2.2591
T2
X7.1207Y-2.1398
X7.3352Y-2.1398
T3
X4.0827Y-2.4645
X4.0827Y-4.2833
T0
M30
