M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Tue 07 Feb 2023 02:17:05 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-07T14:17:05-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X7.1325Y-2.2591
X7.3234Y-2.2591
T2
X7.1207Y-2.1398
X7.3352Y-2.1398
T3
X3.7598Y-2.4647
X3.7598Y-4.2835
T0
M30
